package repository

var dontEscape = [256]bool{
	false, // 0x0
	false, // 0x1
	false, // 0x2
	false, // 0x3
	false, // 0x4
	false, // 0x5
	false, // 0x6
	false, // 0x7
	false, // 0x8
	false, // 0x9
	false, // 0xA
	false, // 0xB
	false, // 0xC
	false, // 0xD
	false, // 0xE
	false, // 0xF
	false, // 0x10
	false, // 0x11
	false, // 0x12
	false, // 0x13
	false, // 0x14
	false, // 0x15
	false, // 0x16
	false, // 0x17
	false, // 0x18
	false, // 0x19
	false, // 0x1A
	false, // 0x1B
	false, // 0x1C
	false, // 0x1D
	false, // 0x1E
	false, // 0x1F
	false, // 0x20
	false, // 0x21
	false, // 0x22
	false, // 0x23
	true,  // '$'
	false, // 0x25
	true,  // '&'
	false, // 0x27
	false, // 0x28
	false, // 0x29
	false, // 0x2A
	true,  // '+'
	false, // 0x2C
	true,  // '-'
	true,  // '.'
	true,  // '/'
	true,  // '0'
	true,  // '1'
	true,  // '2'
	true,  // '3'
	true,  // '4'
	true,  // '5'
	true,  // '6'
	true,  // '7'
	true,  // '8'
	true,  // '9'
	true,  // ':'
	false, // 0x3B
	false, // 0x3C
	true,  // '='
	false, // 0x3E
	false, // 0x3F
	true,  // '@'
	true,  // 'A'
	true,  // 'B'
	true,  // 'C'
	true,  // 'D'
	true,  // 'E'
	true,  // 'F'
	true,  // 'G'
	true,  // 'H'
	true,  // 'I'
	true,  // 'J'
	true,  // 'K'
	true,  // 'L'
	true,  // 'M'
	true,  // 'N'
	true,  // 'O'
	true,  // 'P'
	true,  // 'Q'
	true,  // 'R'
	true,  // 'S'
	true,  // 'T'
	true,  // 'U'
	true,  // 'V'
	true,  // 'W'
	true,  // 'X'
	true,  // 'Y'
	true,  // 'Z'
	false, // 0x5B
	true,  // '\'
	false, // 0x5D
	false, // 0x5E
	true,  // '_'
	false, // 0x60
	true,  // 'a'
	true,  // 'b'
	true,  // 'c'
	true,  // 'd'
	true,  // 'e'
	true,  // 'f'
	true,  // 'g'
	true,  // 'h'
	true,  // 'i'
	true,  // 'j'
	true,  // 'k'
	true,  // 'l'
	true,  // 'm'
	true,  // 'n'
	true,  // 'o'
	true,  // 'p'
	true,  // 'q'
	true,  // 'r'
	true,  // 's'
	true,  // 't'
	true,  // 'u'
	true,  // 'v'
	true,  // 'w'
	true,  // 'x'
	true,  // 'y'
	true,  // 'z'
	false, // 0x7B
	false, // 0x7C
	false, // 0x7D
	true,  // '~'
	false, // 0x7F
	false, // 0x80
	false, // 0x81
	false, // 0x82
	false, // 0x83
	false, // 0x84
	false, // 0x85
	false, // 0x86
	false, // 0x87
	false, // 0x88
	false, // 0x89
	false, // 0x8A
	false, // 0x8B
	false, // 0x8C
	false, // 0x8D
	false, // 0x8E
	false, // 0x8F
	false, // 0x90
	false, // 0x91
	false, // 0x92
	false, // 0x93
	false, // 0x94
	false, // 0x95
	false, // 0x96
	false, // 0x97
	false, // 0x98
	false, // 0x99
	false, // 0x9A
	false, // 0x9B
	false, // 0x9C
	false, // 0x9D
	false, // 0x9E
	false, // 0x9F
	false, // 0xA0
	false, // 0xA1
	false, // 0xA2
	false, // 0xA3
	false, // 0xA4
	false, // 0xA5
	false, // 0xA6
	false, // 0xA7
	false, // 0xA8
	false, // 0xA9
	false, // 0xAA
	false, // 0xAB
	false, // 0xAC
	false, // 0xAD
	false, // 0xAE
	false, // 0xAF
	false, // 0xB0
	false, // 0xB1
	false, // 0xB2
	false, // 0xB3
	false, // 0xB4
	false, // 0xB5
	false, // 0xB6
	false, // 0xB7
	false, // 0xB8
	false, // 0xB9
	false, // 0xBA
	false, // 0xBB
	false, // 0xBC
	false, // 0xBD
	false, // 0xBE
	false, // 0xBF
	false, // 0xC0
	false, // 0xC1
	false, // 0xC2
	false, // 0xC3
	false, // 0xC4
	false, // 0xC5
	false, // 0xC6
	false, // 0xC7
	false, // 0xC8
	false, // 0xC9
	false, // 0xCA
	false, // 0xCB
	false, // 0xCC
	false, // 0xCD
	false, // 0xCE
	false, // 0xCF
	false, // 0xD0
	false, // 0xD1
	false, // 0xD2
	false, // 0xD3
	false, // 0xD4
	false, // 0xD5
	false, // 0xD6
	false, // 0xD7
	false, // 0xD8
	false, // 0xD9
	false, // 0xDA
	false, // 0xDB
	false, // 0xDC
	false, // 0xDD
	false, // 0xDE
	false, // 0xDF
	false, // 0xE0
	false, // 0xE1
	false, // 0xE2
	false, // 0xE3
	false, // 0xE4
	false, // 0xE5
	false, // 0xE6
	false, // 0xE7
	false, // 0xE8
	false, // 0xE9
	false, // 0xEA
	false, // 0xEB
	false, // 0xEC
	false, // 0xED
	false, // 0xEE
	false, // 0xEF
	false, // 0xF0
	false, // 0xF1
	false, // 0xF2
	false, // 0xF3
	false, // 0xF4
	false, // 0xF5
	false, // 0xF6
	false, // 0xF7
	false, // 0xF8
	false, // 0xF9
	false, // 0xFA
	false, // 0xFB
	false, // 0xFC
	false, // 0xFD
	false, // 0xFE
	false, // 0xFF
}
